version: '3'

services:
  node_app:
    image: suatanbantru-be
    ports:
      - 6000:3002
    environment:
      - ENV_PORT=3002
      - MINIO_ACCESS_KEY=thong
      - MINIO_PRIVATE_KEY=Thong28101994@
      - MINIO_ENDPOINT=45.117.177.212
      - MINIO_PORT=9000
      - SECRET_KEY= thong28101994@
    restart: always
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - 8070:8070
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - node_app